### ISSUE TITLE
TypeErrors: jwtString.split and this._next are not functions

### ISSUE THREAD

**Issue by primitive-type** [dwyl/hapi-auth-jwt2#73]
After upgrading from version 4.6.x to 4.7x or 4.8.x I get the following error when running my tests:

```sh
Debug: internal, implementation, error 
    TypeError: jwtString.split is not a function
    at Object.JWT.verify (/.../node_modules/jsonwebtoken/index.js:115:25)
    at /.../node_modules/hapi-auth-jwt2/lib/index.js:39:13
    at keyFunc (/.../node_modules/hapi-auth-jwt2/lib/index.js:30:104)
    at Object.authenticate (/.../node_modules/hapi-auth-jwt2/lib/index.js:31:7)
    at /.../node_modules/hapi/lib/auth.js:227:30
    at internals.Protect.run (/.../node_modules/hapi/lib/protect.js:56:5)
    at authenticate (/.../node_modules/hapi/lib/auth.js:218:26)
    at internals.Auth._authenticate (/.../node_modules/hapi/lib/auth.js:348:5)
    at internals.Auth.authenticate (/.../node_modules/hapi/lib/auth.js:177:17)
    at /.../node_modules/hapi/lib/request.js:370:13
    at iterate (/.../node_modules/hapi/node_modules/items/lib/index.js:35:13)
    at done (/.../node_modules/hapi/node_modules/items/lib/index.js:27:25)
    at /.../node_modules/hapi/node_modules/hoek/lib/index.js:841:22
    at doNTCallback0 (node.js:408:9)
    at process._tickDomainCallback (node.js:378:13)
```

Additionally, the following error also appears a few times during my tests and seems to be related: 

```sh
Debug: internal, implementation, error 
    TypeError: Uncaught error: this._next is not a function
    at Function.internals.response (/.../node_modules/hapi/lib/reply.js:137:14)
    at reply (/.../node_modules/hapi/lib/reply.js:68:22)
    at /.../node_modules/hapi-auth-jwt2/lib/index.js:44:20
    at /.../node_modules/jsonwebtoken/index.js:101:18
    at doNTCallback0 (node.js:408:9)
    at process._tickDomainCallback (node.js:378:13)
```

My version of hapi is 8.8.1. Everything works perfectly for me up to and including version 4.6.x of hapi-auth-jwt2.

**Comment by nelsonic** [comment]
@primitive-type thanks for pasting the stack trace. We are looking into it now.

**Comment by nelsonic** [comment]
is your JWT key a string or a number?

**Comment by alanshaw** [comment]
I'm seeing both these errors as well.

The first is appearing when the route is secured and the client sends no Authorization header.

The second is appearing when I have `mode: 'try'` and no Authorization header is sent.

**Comment by electerious** [comment]
I'm not sure if my error is related to the one mentioned above, but I get the following when trying to access a route:

```
Debug: internal, implementation, error 
    TypeError: undefined is not a function
    at Object.JWT.verify (/Users/tobiasreich/Sites/Ackee/core/node_modules/hapi-auth-jwt2/node_modules/jsonwebtoken/index.js:115:25)
    at /Users/tobiasreich/Sites/Ackee/core/node_modules/hapi-auth-jwt2/lib/index.js:39:13
    at keyFunc (/Users/tobiasreich/Sites/Ackee/core/node_modules/hapi-auth-jwt2/lib/index.js:30:104)
    at Object.authenticate (/Users/tobiasreich/Sites/Ackee/core/node_modules/hapi-auth-jwt2/lib/index.js:31:7)
    at /Users/tobiasreich/Sites/Ackee/core/node_modules/hapi/lib/auth.js:227:30
    at internals.Protect.run (/Users/tobiasreich/Sites/Ackee/core/node_modules/hapi/lib/protect.js:56:5)
    at authenticate (/Users/tobiasreich/Sites/Ackee/core/node_modules/hapi/lib/auth.js:218:26)
    at internals.Auth._authenticate (/Users/tobiasreich/Sites/Ackee/core/node_modules/hapi/lib/auth.js:348:5)
    at internals.Auth.authenticate (/Users/tobiasreich/Sites/Ackee/core/node_modules/hapi/lib/auth.js:177:17)
    at /Users/tobiasreich/Sites/Ackee/core/node_modules/hapi/lib/request.js:370:13
```

Happens on every request, but the server still returns a correct response:

```
{"statusCode":401,"error":"Unauthorized","message":"Missing auth token"}
```

Here's a small look at my implementation:

```
let plugin = require('hapi-auth-jwt2')

server.register(plugin, (err) => {

	if (err) {
		next(err)
		return false
	}

	server.auth.strategy('jwt', 'jwt', true, {
		key           : 'asdasdasdasdasdasd',
		validateFunc  :function(decoded, request, next) {
		    console.log('test')
		    return next(null, false)
		},
		verifyOptions : { algorithms: ['HS256'] }
	})

	console.log('test2')
	next(null)

})
```

Console never says 'test', but 'test2'.

Let me know if you need more information or if I should open a separate issue. Thanks! :)

**Comment by nelsonic** [comment]
The conditions @alanshaw is describing `mode: 'try'` and **no Authorization header** are covered by the lines:
https://github.com/dwyl/hapi-auth-jwt2/blob/f62bf57795e22b97f5c31a2375b68d6e7e6b80e1/lib/extract.js#L27-L29

which used to be in index.js:
https://github.com/dwyl/hapi-auth-jwt2/blob/da48ca516272b446e78766d59057dc930474ace1/lib/index.js#L41-L43

**Comment by primitive-type** [comment]
@nelsonic Sorry for getting back to you so late. My JWT key is a string.

**Comment by nelsonic** [comment]
@primitive-type Ok. I'm trying to re-create the circumstances locally. 
please confirm the version of node you are running.

**Comment by alanshaw** [comment]
@nelsonic I see extract calling `reply.continue` as you posted in the code above, but then the return value for extract (undefined) works it's way down to this line in lib/index.js (can't link since there's no release tags and the code has changed in the repo):

```js
return reply(Boom.unauthorized('Invalid token', 'Token'), null, { credentials: null });
```

This is the line where the error is originating from:

```
    TypeError: this._next is not a function
    at Function.internals.response (/Users/alan/Code/project/project-api/node_modules/hapi/lib/reply.js:137:14)
    at reply (/Users/alan/Code/project/project-api/node_modules/hapi/lib/reply.js:68:22)
    at /Users/alan/Code/project/project-api/node_modules/hapi-auth-jwt2/lib/index.js:44:20
```

**Comment by primitive-type** [comment]
@nelsonic I'm currently running io.js 2.5.0 but also tested with io.js 2.3.4 and there was no difference. Additionally, I can confirm that the two cases of ```TypeError: Uncaught error: this._next is not a function``` were happening on hapi routes where I set ```route.config.auth = {mode: 'optional'};```

**Comment by nelsonic** [comment]
@electerious the issue you have posted *might* be related.
I've created a branch to try and debug this issue. 
tried to write a basic server using the code you pasted.
see: https://github.com/dwyl/hapi-auth-jwt2/blob/debug-issue-73/test/issue-73-server.js

but get error:
```sh
/hapi-auth-jwt2/test/issue-73-server.js:30
    next(null)
    ^
ReferenceError: next is not defined
    at /hapi-auth-jwt2/test/issue-73-server.js:30:5
```

Which refers to the fact that you are calling `next(err)` in your server error handler.

**Comment by primitive-type** [comment]
@nelsonic I just ran my tests with io.js 1.8.1 and still got the same errors.

**Comment by alanshaw** [comment]
`extract` is doing way more than just extracting a token from the request. It might extract the token, or it might respond to the client! Surprise!

**Comment by nelsonic** [comment]
@alanshaw yes, the lack of release tags have been duly noted. #72 
Also, yes, `extract` responds early if there is no token.

**Comment by nelsonic** [comment]
@primitive-type @electerious @alanshaw 
this is my *exclusive* focus until it gets resolved.
please hang tight and use V.4.4.0  (before tokens in urls or cookies) until I inform otherwise.
Thanks for your patience. :+1:

**Comment by primitive-type** [comment]
@nelsonic Thanks very much for being so on top of this. Just to clarify, I've been using version 4.6.0 successfully since I ran into this issue. Tokens in URLs seem to be working fine in my app. Any reason I shouldn't be using that version?

**Comment by nelsonic** [comment]
@primitive-type `4.6.0` should still be fine. thanks.

**Comment by nelsonic** [comment]
Ok, I was able to reproduce the problem: https://travis-ci.org/dwyl/hapi-auth-jwt2-example/jobs/73599511 
diving into fixing it now.

**Comment by nelsonic** [comment]
Github closed this issue via commit message parsing ... see: https://help.github.com/articles/closing-issues-via-commit-messages/

**Comment by nelsonic** [comment]
@primitive-type  & @electerious please update to `v.4.8.1` and inform us if you are still seeing the error you reported. thanks! :pray:

**Comment by primitive-type** [comment]
@nelsonic I'm no longer seeing the errors I reported. Everything seems to be working well now! Thanks again for being so on top of this.

**Comment by nelsonic** [comment]
@primitive-type thanks for confirming you no longer see the issue.
all credit/props go to @alanshaw who is a coding Wizard you should follow everywhere!
+ https://github.com/alanshaw
+ https://twitter.com/_alanshaw

@electerious please confirm its fixed for you so we can close the issue. :+1:

**Comment by electerious** [comment]
@nelsonic Everything works file now. Thanks for the help! :)

**Comment by nelsonic** [comment]
@electerious thanks!
once again, 
@primitive-type thanks for ***reporting*** the issue!
and @alanshaw for fixing it!
:tada:
